spring.application.name=service-notes
# Configuration du port du serveur Tomcat
server.port = 8083

# Connexion JPA à la base de données
spring.datasource.primary.jdbc-url = jdbc:postgresql://127.0.0.1:5432/bddnote
spring.datasource.primary.username = postgres
spring.datasource.primary.password= root
spring.datasource.primary.driver-class-name=org.postgresql.Driver

# Secondary DataSource (for encryption keys)
spring.datasource.secondary.jdbc-url=jdbc:postgresql://127.0.0.1:5432/bddprivatekeynotes
spring.datasource.secondary.username=postgres
spring.datasource.secondary.password=root
spring.datasource.secondary.driver-class-name=org.postgresql.Driver

# JPA Properties for primary DataSource
spring.jpa.primary.hibernate.ddl-auto=update
spring.jpa.primary.show-sql=true
spring.jpa.primary.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JPA Properties for secondary DataSource
spring.jpa.secondary.hibernate.ddl-auto=update
spring.jpa.secondary.show-sql=true
spring.jpa.secondary.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Configuration Kafka
spring.cloud.stream.kafka.binder.brokers=localhost:9092

# Configuration pour la production de logs vers Kafka
spring.cloud.stream.bindings.logOutput-out-0.destination=note-logs

# Configuration pour la consommation de logs depuis Kafka
spring.cloud.stream.bindings.logInput-in-0.destination=note-logs
spring.cloud.stream.bindings.logInput-in-0.group=service-notes