server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: route1
          uri: http://localhost:8081
          predicates:
            - Path=/api/compte

        - id: route2
          uri: http://localhost:8082
          predicates:
            - Path=/api/utilisateur

#   application:
#     name: gateway

# eureka:
#   instance:
#     non-secure-port: 8080

# logging:
#   level:
#     org.springframework.web.cors: DEBUG
#     org.springframework.cloud.gateway: DEBUG
