# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #service: [service-utilisateur, service-notes, service-compte, service-gestion-password]  # Liste des microservices à analyser
        service: [service-utilisateur, service-compte, service-gestion-password,service-notes]  # Liste des microservices à analyser
        #service: [service-utilisateur]  # Liste des microservices à analyser

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test SonarQube connectivity
        run: |
          curl -v ${{ secrets.SONAR_HOST_URL }}

      - name: Code coverage & scan SonarQube & packaging JAR
        run: >
          mvn -f ${{ matrix.service }}/pom.xml
          org.jacoco:jacoco-maven-plugin:prepare-agent
          package
          verify
          org.jacoco:jacoco-maven-plugin:report
          sonar:sonar
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
          -Dsonar.projectKey=projet-${{ matrix.service }}
          -Dsonar.projectName=projet-${{ matrix.service }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Qualité SonarQube
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        with:
          scanMetadataReportFile: ${{ matrix.service }}/target/sonar/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Partage du fichier JAR
        uses: actions/upload-artifact@v3
        with:
          name: appjar-${{ matrix.service }}
          path: ${{ matrix.service }}/target/*.jar
   
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ service-utilisateur, service-compte, service-gestion-password,service-notes]

    steps:
      - name: Checkout du projet
        uses: actions/checkout@v4
      
      - name: Récupération du fichier JAR
        uses: actions/download-artifact@v3
        with:
          name: appjar-${{ matrix.service }}
          path: ${{ matrix.service }}/target

      - name: Afficher le contenu du répertoire de chaque service
        run: |
          echo "Contenu du répertoire ${{ matrix.service }}:"
          ls -R ${{ matrix.service }}

      - name: Installation QEMU
        uses: docker/setup-qemu-action@v3

      - name: Installation Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Connexion au Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_GITHUB }}

      - name: Build de l'image & Push de l'image sur le Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}  # Utilisez le dossier du microservice comme contexte
          file: ${{ matrix.service }}/Dockerfile  # Chemin relatif correct vers le Dockerfile
          push: true
          tags: saousane/ajc-soutenance:java-${{ matrix.service }}
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Préparation de la connexion SSH vers notre machine
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Commandes pour info à exécuter sur la machine distante
        run: >
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
          "
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN_SERVER }}
            docker stop ajc-soutenance-password || true
            docker rm ajc-soutenance-password || true
            docker run -d -p 8081:8080 --name ajc-soutenance-password  --pull=always saousane/ajc-soutenance:java-service-gestion-password
            docker stop ajc-soutenance-utilisateur || true
            docker rm ajc-soutenance-utilisateur || true
            docker run -d -p 8086:8080 --name ajc-soutenance-utilisateur --pull=always saousane/ajc-soutenance:java-service-utilisateur
            docker stop ajc-soutenance-note || true
            docker rm ajc-soutenance-note || true
            docker run -d -p 8083:8080 --name ajc-soutenance-note --pull=always saousane/ajc-soutenance:java-service-notes
            docker stop ajc-soutenance-compte || true
            docker rm ajc-soutenance-compte || true
            docker run -d -p 8084:8080 --name ajc-soutenance-compte --pull=always saousane/ajc-soutenance:java-service-compte
            exit
          "
      - name: Nettoyage
        run: rm -rf ~/.ssh
          